# Generated by Django 4.0.3 on 2022-03-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_answer_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='technique',
        ),
    ]
