# Generated by Django 4.0.3 on 2022-03-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='is_active',
        ),
    ]
