# Generated by Django 4.0.3 on 2022-03-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
